name: Extract IPs from ipTop10.html

on:
  push:
    paths:
      - 'ipTop10.html'

jobs:
  extract-ips:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Extract IPs from ipTop10.html
      id: extract-ips
      run: |
        # 读取 ipTop10.html 文件内容
        IP_LIST=$(cat ipTop10.html)

        # 将逗号分隔的 IP 地址拆分为多行
        echo "$IP_LIST" | tr ',' '\n' > cfip.txt

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add cfip.txt
        git commit -m "Update cfip.txt with latest IPs from ipTop10.html"
        git push