name: Update cfip.txt from ipTop10.html

on:
  push:
    paths:
      - ipTop10.html

jobs:
  update-ip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract IPs and update cfip.txt
        run: |
          # 读取 ipTop10.html 内容，将逗号替换为换行符，生成 cfip.txt
          tr ',' '\n' < ipTop10.html > cfip.txt
          echo "cfip.txt 更新完成，内容如下："
          cat cfip.txt

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add cfip.txt
          # 如果没有变更，则不会报错
          git commit -m "Update cfip.txt with IP addresses" || echo "No changes to commit"
          git push
