name: Update DNS IP List

on:
  push:
    paths:
      - 'ipTop10.html'

jobs:
  process-ips:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Extract and format IPs
      run: |
        # 提取IP并格式化（逗号转行、去空格、去重、排序）
        if [ -f ipTop10.html ]; then
          cat ipTop10.html | tr ',' '\n' | sed 's/ //g' | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}' | sort -u > cfip.txt
        else
          echo "ipTop10.html not found!"
          exit 1
        fi

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        add: cfip.txt
        message: "Update CF IP list"
        name: "DNS Pod Updater"
        email: "actions@github.com"