name: IP List Maintainer

on:
  push:
    paths:
      - 'ipTop10.html'  # 路径需与实际存储位置完全匹配

jobs:
  ip-processor:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 关键权限：允许自动提交

    steps:
      # 步骤1：获取代码
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # 禁用默认凭证缓存

      # 步骤2：IP提取引擎
      - name: IP Extraction
        run: |
          # 使用加强型正则匹配严格过滤合法IP
          grep -Eo '(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])(\.(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])){3}' ipTop10.html \
          | awk '!seen[$0]++' \  # 高效去重替代sort -u
          > cfip.txt

      # 步骤3：智能提交系统
      - name: Auto-Commit
        uses: EndBug/[email protected]
        with:
          branch: main  # 根据实际分支名称修改
          empty-commit: false
          add: 'cfip.txt'
          message: 'chore: Auto-sync IP database'
          token: ${{ secrets.GITHUB_TOKEN }}
